name: casanet dashboard app CI CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1 
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Bundle www # The assets build for the public CDN
      env:
        BUILD_PATH: www
        API_URL_PROD: '${{ secrets.API_URL }}'
        API_URL_DEV: '${{ secrets.API_URL_DEV }}'
        V3_URL_PROD: '${{ secrets.V3_URL }}'
        V3_URL_DEV: '${{ secrets.V3_URL_DEV }}'
      run: |
        export ON_BRANCH=${GITHUB_REF##*/}
        if [[ $ON_BRANCH == 'main' ]]; then export REACT_APP_API_URL=$API_URL_PROD ; else export REACT_APP_API_URL=$API_URL_DEV; fi
        if [[ $ON_BRANCH == 'main' ]]; then export REACT_APP_V3_URL=$V3_URL_PROD ; else export REACT_APP_V3_URL=$V3_URL_DEV; fi
        npm i -g yarn
        yarn install --frozen-lockfile
        yarn run postbuild
    - uses: actions/upload-artifact@v2
      with:
        name: www
        path: www

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Fix Android SDK 31 # https://stackoverflow.com/questions/68387270/android-studio-error-installed-build-tools-revision-31-0-0-is-corrupted
      run: |
        cd $ANDROID_HOME/build-tools/31.0.0 && cp d8 dx && cd lib && cp d8.jar dx.jar

    - name: Bundle Android APP
      env:
        BUILD_PATH: www
      run: |
        npm i -g cordova
        cordova platform add android
        npm run android
    - uses: actions/upload-artifact@v2
      with:
        name: android 
        path: platforms/android/app/build/outputs/apk

    - name: Bundle internal # The assets build for the local server, the api server is just ''
      env:
        REACT_APP_API_URL: ''
        REACT_APP_V3_URL: ''
        BUILD_PATH: internal
      run: |
        yarn run build
        yarn run postbuild
    - uses: actions/upload-artifact@v2
      with:
        name: internal 
        path: internal
