name: casanet dashboard app CI CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1 
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Bundle www # The assets build for the public CDN
      env:
        BUILD_PATH: www
        API_URL_PROD: '${{ secrets.API_URL }}'
        API_URL_DEV: '${{ secrets.API_URL_DEV }}'
        V3_URL_PROD: '${{ secrets.V3_URL }}'
        V3_URL_DEV: '${{ secrets.V3_URL_DEV }}'
        LIGHTWEIGHT_URL_PROD: '${{ secrets.LIGHTWEIGHT_URL }}'
        LIGHTWEIGHT_URL_DEV: '${{ secrets.LIGHTWEIGHT_URL_DEV }}'
      run: |
        export ON_BRANCH=${GITHUB_REF##*/}
        if [[ $ON_BRANCH == 'main' ]]; then export REACT_APP_API_URL=$API_URL_PROD ; else export REACT_APP_API_URL=$API_URL_DEV; fi
        if [[ $ON_BRANCH == 'main' ]]; then export REACT_APP_V3_URL=$V3_URL_PROD ; else export REACT_APP_V3_URL=$V3_URL_DEV; fi
        if [[ $ON_BRANCH == 'main' ]]; then export REACT_APP_LIGHTWEIGHT_URL=$LIGHTWEIGHT_URL_PROD ; else export REACT_APP_LIGHTWEIGHT_URL=$LIGHTWEIGHT_URL_DEV; fi
        npm i -g yarn
        yarn install --frozen-lockfile
        yarn run postbuild
    - uses: actions/upload-artifact@v2
      with:
        name: www
        path: www

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Fix Android SDK 31 # https://stackoverflow.com/questions/68387270/android-studio-error-installed-build-tools-revision-31-0-0-is-corrupted
      run: |
        cd $ANDROID_HOME/build-tools/31.0.0 && cp d8 dx && cd lib && cp d8.jar dx.jar

    - name: Bundle Android APP
      env:
        REACT_APP_API_URL: '${{ secrets.API_URL_DEMO }}'
        REACT_APP_V3_URL: '${{ secrets.V3_URL_APP }}'
        REACT_APP_LIGHTWEIGHT_URL: '${{ secrets.LIGHTWEIGHT_URL_APP }}'
        CASANET_KEY_STORE: '${{ secrets.CASANET_KEY_STORE }}'
        CASANET_KEY_ALIAS: '${{ secrets.CASANET_KEY_ALIAS }}'
        CASANET_KEY_PASSWORD: '${{ secrets.CASANET_KEY_PASSWORD }}'
        BUILD_PATH: www
      run: |
        yarn run build
        yarn run postbuild
        npm i -g cordova
        node scripts/decode-key-store.js
        cordova platform add android
        cordova build android --release -- --keystore=casanet-key-store.jks --storePassword=$CASANET_KEY_PASSWORD --alias=$CASANET_KEY_ALIAS --password=$CASANET_KEY_PASSWORD
    - uses: actions/upload-artifact@v2
      with:
        name: android 
        path: platforms/android/app/build/outputs/apk

    - name: Bundle internal # The assets build for the local server, the api server is just ''
      env:
        REACT_APP_API_URL: ''
        REACT_APP_V3_URL: ''
        REACT_APP_LIGHTWEIGHT_URL: ''
        BUILD_PATH: internal
      run: |
        yarn run build
        yarn run postbuild
    - uses: actions/upload-artifact@v2
      with:
        name: internal 
        path: internal
  
  bomb_version:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    # if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Update Version Patch
      id: update_version
      run: |
          npm i -g yarn
          yarn install --frozen-lockfile
          npm run patchversion
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo $PACKAGE_VERSION
          echo ::set-output name=version::$PACKAGE_VERSION
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Update to version ${{ steps.update_version.outputs.version }} [ci skip]
  
  release:
    needs: bomb_version 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    # if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: android
        path: android
    - name: Get the version
      id: get_version
      run: |
        echo ::set-output name=version::$(node -p "require('./package.json').version")
        echo ::set-output name=title::$(git log -1 --pretty=%B | sed -n '1p')
        body=$(git log -1 --pretty=%B | sed 1d)
        body="${body//'%'/'%25'}"
        body="${body//$'\n'/'%0A'}"
        body="${body//$'\r'/'%0D'}"
        echo ::set-output name=body::$body
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: ${{  steps.get_version.outputs.title }}
        body: ${{  steps.get_version.outputs.body }}
        draft: false
        prerelease: false
    - name: Upload Release Asset - Android APP
      id: upload-release-asset-android-app
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./android/release/app-release.apk
        asset_name: casanet.apk
        asset_content_type: application/octet-stream

