name: casanet dashboard app CI CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_PATH: www
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1 
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Bundle
      run: |
        npm i -g yarn
        yarn install --frozen-lockfile
        yarn run build
    - uses: actions/upload-artifact@v2
      with:
        name: assets 
        path: www
